airbnb/rheostat

README.md
src/Slider.jsx
stories/ExampleSlider.jsx

Fairly self-explanatory, prevents the user from moving the slider handles when `disabled=true`. I believe this covers the case where the user is moving the handle when it gets disabled, in which case it behaves like a standard HTML slider and stops in place.

Add a prop for disabling the slider

---

package.json
src/Slider.jsx

Lets just use getDOMNode if its available and if its not then we'll assume that the ref is the node itself. This gets rid of the React.version hack. Plus now we're compatible with AFAICT React 12+
@ljharb

Fixes rheostat for React 15

---

test/algorithms/geometric-test.js

This test appears to test the maximum end of the range, as the test before tested the minimum end of the range.

correct test name to maximum instead of minimum

---

README.md
src/Slider.jsx

@backwardok @ljharb 
Hardcoding the tab index to 0 so it addresses the tabbing issue. This removes the previous behavior of having the tab index be configurable. That's ok because it seems like it is best practice to always set to 0 and let DOM layout structure dictate how elements are tabbed to.
More info here: http://webaim.org/techniques/keyboard/tabindex

Sets tabIndex to 0

---

package.json
src/Slider.jsx
test/slider-test.jsx

- Use `prop-types` package instead of `React.PropTypes`
- Replace `React.createClass` with `create-react-class`

[Fix] use prop-types package + replace React.createClass

---

src/Slider.jsx

Hello,
When you are using with [preact](https://github.com/developit/preact) issues can happen when you have an element with the `key={0}`
see: 
* https://github.com/developit/preact/issues/642
* https://github.com/algolia/instantsearch.js/issues/2293
It is a "temporary" fix to make the library used until the issue is originally fixed into preact.

fix(Slider): avoid key={0}

---

package.json
src/Slider.jsx
test/slider-test.jsx

It's allows us to use `React.PureComponent` as PitComponent and don't trigger unnecessary re-renders.

Memoize pits styles

---

src/algorithms/geometric.js
test/algorithms/geometric-test.js

Use `Math.round` instead of `Math.floor` for getting values to fix small increments in positions might not be reflected in the values.
without the fix, the test will fail and yield 357 instead
JIRA comments:
hi @goatslacker , after some debug, I found this bug is due to the Math.floor is being used here. https://github.com/airbnb/rheostat/commit/ac671f34f8bff13579b3fa00e038a2627abc37d2#diff-18b3b4532ad02a3a1b4f629dcd1cebf4R7
If I change it to Math.round it will just work for keyboard press. The reason for the bug is that when value gets larger but not large enough, it gets floored back to the same number. Let me know what you think the best approach here.

Use math.round instead of math.floor for getting value with geomotric

---

CHANGELOG.md
README.md
src/Slider.jsx
test/slider-test.jsx

Addresses https://github.com/airbnb/rheostat/issues/125. Allows us to deny a move depending on the handle index and next value.

Add getNextHandlePosition for complex drag validation

---

src/Slider.jsx
test/slider-test.jsx

When the component is started in a React 16 environment and the `disabled` prop is set to true, React 16 will throw a console warning for each of the functions set via the short circuit logical operators. 
This currently manifests as the following (subset) of warnings logged as console errors:
This PR acts to silence those warnings and prep for the anticipation that React 17 will convert these to throwable errors. Documentation of the changes that introduced these warnings can be found [here](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html#changes-in-detail) under "Non-boolean attributes with boolean values"

Fixes React 16 prop-type Errors

---

.eslintrc
.storybook/config.js
package.json
src/DefaultBackground.jsx
src/DefaultHandle.jsx
src/DefaultProgressBar.jsx
src/Slider.jsx
src/algorithms/linear.js
src/algorithms/log10.js
src/constants/SliderConstants.js
src/propTypes/HandlePropTypes.js
src/propTypes/OrientationPropType.js
src/themes/DefaultTheme.js
stories/ExampleSlider.jsx
test/_setup.js
test/slider-test.jsx

This change moves react-dates onto Airbnb's modern best practices of CSS in your Javascript! Also included are some substantial changes to the internals of the Rheostat component, as well as updates to Rheostat's testing suite (to make the tests pass with the recent changes). 
This PR is *very close* to parity with current version. The following will be addressed (in separate pull requests) in order to finish up the transition, and make it stable / ready for release: 
As a note, this PR also fixed a few bugs in the old version of Rheostat. Including an instance where an empty array was thought to be falsey (ie: `[] || foo`), and an un-noticed propTypes violation. 
Existing tests (updated to account for new component structure) pass, with the exception of the skipped tests mentioned above. …

Upgrade rheostat to react-with-styles (Phase 1) 🎉 

---

.travis.yml
package.json

Fixes CI issue where build script was failing on Node 4. This is because buildCSS.js (which runs during the build process), included/had dependencies which use object destructuring, which is not supported by Node 4. 
To fix this, I introduced a change where build is only run once, and on the newest version of node.
This is required before 
https://github.com/airbnb/rheostat/pull/162
https://github.com/airbnb/rheostat/pull/163
https://github.com/airbnb/rheostat/pull/164
can be merged.

[test] only run build script on latest node version (1/7)

---

package.json
test/algorithms/geometric-test.js

Prevents pre-publish script from running `npm install` in node 4.

update pre-publish script

---

.storybook/config.js
scripts/utils/registerInterfaceWithDefaultTheme.js
src/DefaultHandle.jsx
src/DefaultProgressBar.jsx
src/constants/SliderConstants.js
src/themes/DefaultTheme.js

This commit sits on top of https://github.com/airbnb/rheostat/pull/162, and will be rebased when that commit is merged. 
Cleans up CSS/ the default theme for Rheostat.

Clean up rheostat css theming (3/7)

---

src/DefaultBackground.jsx
src/Slider.jsx

During the port of the internal Rheostat component, the background prop was taken out and placed inline. This prop has been re-added, restoring previous functionality.

[bugfix] reintroduce background prop

---

src/Slider.jsx
src/constants/SliderConstants.js
test/slider-test.jsx

A couple of things were modified in #161. One, we lost the pit style cache (#123, #130) and two there was a strange update to add `step` instead of `snap` (but step wasn't actually used anywhere). This change adds back the cache and also consolidates on the `snap` API (including a small fix to how position was being set).
I also opened https://github.com/airbnb/rheostat/issues/176 to track the issue that `step` was intended to address. 
to: @ljharb @philipfweiss @airbnb/webinfra

Add back pitStyle cache and remove step prop

---

src/Slider.jsx
test/slider-test.jsx

Fixes #137
This no longer triggers the onChange handler when values (or min/max) are programmatically updated. I tested this on @madou's example repo: https://github.com/madou/rheostat-double-onchange/. Note that normal behavior continues as expected. The `updateNewValues` method only gets called by 1componentWillReceiveProps`.
to: @ljharb @airbnb/webinfra

Do not trigger change event when programmatically updating the slider values

---

.storybook-css/config.js
.storybook/config.js
scripts/buildCSS.js
scripts/utils/registerCSSInterfaceWithDefaultTheme.js
scripts/utils/registerInterfaceWithDefaultTheme.js
src/initialize.js
src/utils/.eslintrc
src/utils/registerCSSInterfaceWithDefaultTheme.js
src/utils/registerInterfaceWithDefaultTheme.js

Addresses https://github.com/airbnb/rheostat/issues/181. Moves the theme registration helper functions into src, so they will be compiled during the build step. Also updates the callsites of these functions to point into `lib/utils/<x>`, as desired. 
Keeps a copy of these files in `scripts/utils` as well, for backwards-compatibility. These files should be removed at the next major version update.

[fix] Move theme registration to src

---

src/Slider.jsx
test/slider-test.jsx

This PR fixes handle's position calculations for vertical mode.

Fix position calculations for 'vertical' mode

---

README.md
package.json
src/DefaultHandle.jsx
src/DefaultProgressBar.jsx
src/Slider.jsx
stories/ExampleSlider.jsx
test/slider-test.jsx

- Add [`react-with-direction`](https://github.com/airbnb/react-with-direction) to detect RTL/LTR
- Change how styles are passed to default child components
e.g. `DefaultHandle`, `DefaultProgressBar` so they're properly
RLT/LTR-ified
- Change how handle position is calculated based on direction
Also added new storybook examples, some tests, and a note in the docs.

Add RTL support

---

package.json

Updates the version of `react-with-styles` from 4.0.0 to 4.0.1, which uses a `WeakMap` for caching of stylesFn results to avoid high memory usage.
@ljharb @majapw @ahuth @TaeKimJR @indiesquidge @joeuy

[fix][deps] `react-with-styles` 4.0.0 -> 4.0.1

---

src/Slider.jsx
test/slider-test.jsx

I couldn't repro this error, but I think this should fix it.
```js
TypeError: null is not an object (evaluating 'this.handleContainerNode.getBoundingClientRect')
at getSliderBoundingBox (./node_modules/rheostat/lib/Slider.js:325)
at None ([native code])
at touch (./node_modules/rheostat/lib/Slider.js:704)
at None ([native code])
at this (./node_modules/rheostat/lib/Slider.js:677)
...
(2 additional frame(s) were not displayed)
```
By protecting access to `this.handleContainerNode`, we avoid this issue completely.
@ljharb @lencioni 
Airbnb internal ticket: PRODUCT-49741

[Slider] Fix "TypeError: Cannot read 'getBoundingClientRect' of null"

---

package.json

geometric-test.js was being missed from the test run.
before
after

Fix jest test match glob so all test files are picked up
